// Code generated by go generate ./tsdb/chunkenc. DO NOT EDIT.

// Copyright The Prometheus Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build go1.27 && goexperiment.simd && amd64

package chunkenc

import "simd/archsimd"

func alpDecodeAVX512(dst []float64, words []uint64, width int, base int64, factor, exponent uint8) {
	alpAVX512Widths[width](dst, words, width, base, factor, exponent)
}

var alpAVX512Widths = [...]alpKernel{alpDecodeAVX512Generic,
	alpDecodeAVX512Width1,
	alpDecodeAVX512Width2,
	alpDecodeAVX512Width3,
	alpDecodeAVX512Width4,
	alpDecodeAVX512Width5,
	alpDecodeAVX512Width6,
	alpDecodeAVX512Width7,
	alpDecodeAVX512Width8,
	alpDecodeAVX512Width9,
	alpDecodeAVX512Width10,
	alpDecodeAVX512Width11,
	alpDecodeAVX512Width12,
	alpDecodeAVX512Width13,
	alpDecodeAVX512Width14,
	alpDecodeAVX512Width15,
	alpDecodeAVX512Width16,
	alpDecodeAVX512Width17,
	alpDecodeAVX512Width18,
	alpDecodeAVX512Width19,
	alpDecodeAVX512Width20,
	alpDecodeAVX512Width21,
	alpDecodeAVX512Width22,
	alpDecodeAVX512Width23,
	alpDecodeAVX512Width24,
	alpDecodeAVX512Width25,
	alpDecodeAVX512Width26,
	alpDecodeAVX512Width27,
	alpDecodeAVX512Width28,
	alpDecodeAVX512Width29,
	alpDecodeAVX512Width30,
	alpDecodeAVX512Width31,
	alpDecodeAVX512Width32,
	alpDecodeAVX512Width33,
	alpDecodeAVX512Width34,
	alpDecodeAVX512Width35,
	alpDecodeAVX512Width36,
	alpDecodeAVX512Width37,
	alpDecodeAVX512Width38,
	alpDecodeAVX512Width39,
	alpDecodeAVX512Width40,
	alpDecodeAVX512Width41,
	alpDecodeAVX512Width42,
	alpDecodeAVX512Width43,
	alpDecodeAVX512Width44,
	alpDecodeAVX512Width45,
	alpDecodeAVX512Width46,
	alpDecodeAVX512Width47,
	alpDecodeAVX512Width48,
	alpDecodeAVX512Width49,
	alpDecodeAVX512Width50,
	alpDecodeAVX512Width51,
	alpDecodeAVX512Width52,
	alpDecodeAVX512Width53,
	alpDecodeAVX512Width54,
	alpDecodeAVX512Width55,
	alpDecodeAVX512Width56,
	alpDecodeAVX512Width57,
	alpDecodeAVX512Width58,
	alpDecodeAVX512Width59,
	alpDecodeAVX512Width60,
	alpDecodeAVX512Width61,
	alpDecodeAVX512Width62,
	alpDecodeAVX512Width63,
	alpDecodeAVX512Width64,
}

func alpDecodeAVX512Width1(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 1

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width2(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 2

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width3(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 3

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width4(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 4

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width5(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 5

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width6(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 6

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width7(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 7

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width8(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 8

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width9(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 9

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width10(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 10

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width11(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 11

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width12(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 12

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width13(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 13

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width14(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 14

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width15(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 15

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width16(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 16

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width17(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 17

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width18(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 18

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width19(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 19

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width20(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 20

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width21(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 21

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width22(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 22

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width23(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 23

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width24(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 24

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width25(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 25

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width26(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 26

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width27(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 27

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width28(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 28

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width29(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 29

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width30(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 30

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width31(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 31

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width32(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 32

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width33(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 33

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width34(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 34

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width35(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 35

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width36(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 36

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width37(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 37

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width38(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 38

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width39(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 39

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width40(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 40

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width41(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 41

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width42(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 42

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width43(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 43

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width44(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 44

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width45(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 45

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width46(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 46

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width47(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 47

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width48(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 48

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width49(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 49

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width50(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 50

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width51(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 51

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width52(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 52

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width53(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 53

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width54(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 54

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width55(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 55

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width56(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 56

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width57(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 57

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width58(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 58

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width59(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 59

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width60(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 60

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width61(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 61

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width62(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 62

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width63(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 63

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX512Width64(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 64

	mask := archsimd.BroadcastUint64x8(alpMask(width))
	frame := archsimd.BroadcastUint64x8(uint64(base))
	multiplier := archsimd.BroadcastInt64x8(alpFactors[factor])
	scale := archsimd.BroadcastFloat64x8(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 8 {
			x := archsimd.LoadUint64x8(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x8(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			q := x.And(mask).Add(frame).BitsToInt64()
			v := q.Mul(multiplier).ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 8 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}
