// Code generated by go generate ./tsdb/chunkenc. DO NOT EDIT.

// Copyright The Prometheus Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build go1.27 && goexperiment.simd && amd64

package chunkenc

import "simd/archsimd"

func alpDecodeAVX2(dst []float64, words []uint64, width int, base int64, factor, exponent uint8) {
	alpAVX2Widths[width](dst, words, width, base, factor, exponent)
}

var alpAVX2Widths = [...]alpKernel{alpDecodeAVX2Generic,
	alpDecodeAVX2Width1,
	alpDecodeAVX2Width2,
	alpDecodeAVX2Width3,
	alpDecodeAVX2Width4,
	alpDecodeAVX2Width5,
	alpDecodeAVX2Width6,
	alpDecodeAVX2Width7,
	alpDecodeAVX2Width8,
	alpDecodeAVX2Width9,
	alpDecodeAVX2Width10,
	alpDecodeAVX2Width11,
	alpDecodeAVX2Width12,
	alpDecodeAVX2Width13,
	alpDecodeAVX2Width14,
	alpDecodeAVX2Width15,
	alpDecodeAVX2Width16,
	alpDecodeAVX2Width17,
	alpDecodeAVX2Width18,
	alpDecodeAVX2Width19,
	alpDecodeAVX2Width20,
	alpDecodeAVX2Width21,
	alpDecodeAVX2Width22,
	alpDecodeAVX2Width23,
	alpDecodeAVX2Width24,
	alpDecodeAVX2Width25,
	alpDecodeAVX2Width26,
	alpDecodeAVX2Width27,
	alpDecodeAVX2Width28,
	alpDecodeAVX2Width29,
	alpDecodeAVX2Width30,
	alpDecodeAVX2Width31,
	alpDecodeAVX2Width32,
	alpDecodeAVX2Width33,
	alpDecodeAVX2Width34,
	alpDecodeAVX2Width35,
	alpDecodeAVX2Width36,
	alpDecodeAVX2Width37,
	alpDecodeAVX2Width38,
	alpDecodeAVX2Width39,
	alpDecodeAVX2Width40,
	alpDecodeAVX2Width41,
	alpDecodeAVX2Width42,
	alpDecodeAVX2Width43,
	alpDecodeAVX2Width44,
	alpDecodeAVX2Width45,
	alpDecodeAVX2Width46,
	alpDecodeAVX2Width47,
	alpDecodeAVX2Width48,
	alpDecodeAVX2Width49,
	alpDecodeAVX2Width50,
	alpDecodeAVX2Width51,
	alpDecodeAVX2Width52,
	alpDecodeAVX2Width53,
	alpDecodeAVX2Width54,
	alpDecodeAVX2Width55,
	alpDecodeAVX2Width56,
	alpDecodeAVX2Width57,
	alpDecodeAVX2Width58,
	alpDecodeAVX2Width59,
	alpDecodeAVX2Width60,
	alpDecodeAVX2Width61,
	alpDecodeAVX2Width62,
	alpDecodeAVX2Width63,
	alpDecodeAVX2Width64,
}

func alpDecodeAVX2Width1(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 1

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width2(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 2

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width3(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 3

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width4(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 4

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width5(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 5

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width6(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 6

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width7(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 7

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width8(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 8

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width9(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 9

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width10(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 10

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width11(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 11

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width12(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 12

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width13(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 13

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width14(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 14

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width15(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 15

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width16(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 16

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width17(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 17

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width18(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 18

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width19(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 19

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width20(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 20

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width21(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 21

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width22(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 22

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width23(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 23

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width24(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 24

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width25(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 25

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width26(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 26

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width27(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 27

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width28(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 28

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width29(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 29

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width30(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 30

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width31(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 31

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width32(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 32

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width33(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 33

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width34(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 34

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width35(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 35

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width36(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 36

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width37(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 37

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width38(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 38

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width39(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 39

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width40(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 40

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width41(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 41

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width42(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 42

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width43(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 43

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width44(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 44

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width45(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 45

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width46(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 46

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width47(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 47

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width48(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 48

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width49(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 49

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width50(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 50

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width51(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 51

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width52(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 52

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width53(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 53

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width54(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 54

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width55(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 55

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width56(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 56

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width57(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 57

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width58(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 58

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width59(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 59

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width60(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 60

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width61(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 61

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width62(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 62

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width63(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 63

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeAVX2Width64(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 64

	mask := archsimd.BroadcastUint64x4(alpMask(width))
	frame := archsimd.BroadcastUint64x4(uint64(base))
	scale := archsimd.BroadcastFloat64x4(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 4 {
			x := archsimd.LoadUint64x4(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x4(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyAVX2(x, uint64(alpFactors[factor]))
			}
			v := alpInt64ToFloat64AVX2(x).Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 4 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}
