// Code generated by go generate ./tsdb/chunkenc. DO NOT EDIT.

// Copyright The Prometheus Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build go1.27 && goexperiment.simd && arm64

package chunkenc

import "simd/archsimd"

func alpDecodeNEON(dst []float64, words []uint64, width int, base int64, factor, exponent uint8) {
	alpNEONWidths[width](dst, words, width, base, factor, exponent)
}

var alpNEONWidths = [...]alpKernel{alpDecodeNEONGeneric,
	alpDecodeNEONWidth1,
	alpDecodeNEONWidth2,
	alpDecodeNEONWidth3,
	alpDecodeNEONWidth4,
	alpDecodeNEONWidth5,
	alpDecodeNEONWidth6,
	alpDecodeNEONWidth7,
	alpDecodeNEONWidth8,
	alpDecodeNEONWidth9,
	alpDecodeNEONWidth10,
	alpDecodeNEONWidth11,
	alpDecodeNEONWidth12,
	alpDecodeNEONWidth13,
	alpDecodeNEONWidth14,
	alpDecodeNEONWidth15,
	alpDecodeNEONWidth16,
	alpDecodeNEONWidth17,
	alpDecodeNEONWidth18,
	alpDecodeNEONWidth19,
	alpDecodeNEONWidth20,
	alpDecodeNEONWidth21,
	alpDecodeNEONWidth22,
	alpDecodeNEONWidth23,
	alpDecodeNEONWidth24,
	alpDecodeNEONWidth25,
	alpDecodeNEONWidth26,
	alpDecodeNEONWidth27,
	alpDecodeNEONWidth28,
	alpDecodeNEONWidth29,
	alpDecodeNEONWidth30,
	alpDecodeNEONWidth31,
	alpDecodeNEONWidth32,
	alpDecodeNEONWidth33,
	alpDecodeNEONWidth34,
	alpDecodeNEONWidth35,
	alpDecodeNEONWidth36,
	alpDecodeNEONWidth37,
	alpDecodeNEONWidth38,
	alpDecodeNEONWidth39,
	alpDecodeNEONWidth40,
	alpDecodeNEONWidth41,
	alpDecodeNEONWidth42,
	alpDecodeNEONWidth43,
	alpDecodeNEONWidth44,
	alpDecodeNEONWidth45,
	alpDecodeNEONWidth46,
	alpDecodeNEONWidth47,
	alpDecodeNEONWidth48,
	alpDecodeNEONWidth49,
	alpDecodeNEONWidth50,
	alpDecodeNEONWidth51,
	alpDecodeNEONWidth52,
	alpDecodeNEONWidth53,
	alpDecodeNEONWidth54,
	alpDecodeNEONWidth55,
	alpDecodeNEONWidth56,
	alpDecodeNEONWidth57,
	alpDecodeNEONWidth58,
	alpDecodeNEONWidth59,
	alpDecodeNEONWidth60,
	alpDecodeNEONWidth61,
	alpDecodeNEONWidth62,
	alpDecodeNEONWidth63,
	alpDecodeNEONWidth64,
}

func alpDecodeNEONWidth1(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 1

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth2(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 2

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth3(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 3

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth4(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 4

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth5(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 5

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth6(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 6

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth7(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 7

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth8(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 8

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth9(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 9

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth10(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 10

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth11(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 11

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth12(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 12

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth13(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 13

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth14(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 14

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth15(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 15

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth16(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 16

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth17(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 17

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth18(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 18

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth19(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 19

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth20(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 20

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth21(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 21

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth22(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 22

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth23(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 23

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth24(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 24

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth25(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 25

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth26(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 26

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth27(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 27

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth28(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 28

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth29(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 29

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth30(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 30

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth31(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 31

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth32(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 32

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth33(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 33

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth34(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 34

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth35(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 35

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth36(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 36

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth37(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 37

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth38(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 38

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth39(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 39

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth40(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 40

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth41(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 41

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth42(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 42

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth43(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 43

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth44(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 44

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth45(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 45

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth46(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 46

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth47(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 47

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth48(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 48

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth49(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 49

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth50(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 50

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth51(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 51

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth52(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 52

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth53(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 53

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth54(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 54

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth55(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 55

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth56(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 56

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth57(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 57

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth58(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 58

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth59(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 59

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth60(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 60

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth61(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 61

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth62(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 62

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth63(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 63

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}

func alpDecodeNEONWidth64(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {
	const width = 64

	mask := archsimd.BroadcastUint64x2(alpMask(width))
	frame := archsimd.BroadcastUint64x2(uint64(base))
	scale := archsimd.BroadcastFloat64x2(alpFractions[exponent])
	for row := 0; row*alpLanes < len(dst); row++ {
		bit := row * width
		word, shift := (bit/64)*alpLanes, uint64(bit%64)
		for lane := 0; lane < alpLanes && row*alpLanes+lane < len(dst); lane += 2 {
			x := archsimd.LoadUint64x2(words[word+lane:]).ShiftAllRight(shift)
			if shift+uint64(width) > 64 {
				x = x.Or(archsimd.LoadUint64x2(words[word+lane+alpLanes:]).ShiftAllLeft(64 - shift))
			}
			x = x.And(mask).Add(frame)
			if factor != 0 {
				x = alpMultiplyNEON(x, uint64(alpFactors[factor]))
			}
			v := x.BitsToInt64().ConvertToFloat64().Mul(scale)
			out := dst[row*alpLanes+lane:]
			if len(out) >= 2 {
				v.Store(out)
			} else {
				v.StorePart(out)
			}
		}
	}
}
