// Copyright The Prometheus Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Command alpgen specializes the reviewed generic SIMD kernels by bit width.
// Run it from tsdb/chunkenc using go generate.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

func main() {
	for _, backend := range []struct{ arch, name string }{{"arm64", "NEON"}, {"amd64", "AVX2"}, {"amd64", "AVX512"}} {
		if err := generate(backend.arch, backend.name); err != nil {
			panic(err)
		}
	}
}

func generate(arch, name string) error {
	src, err := os.ReadFile("alp_decode_" + arch + ".go")
	if err != nil {
		return err
	}
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "kernel.go", src, parser.ParseComments)
	if err != nil {
		return err
	}
	var body []byte
	for _, decl := range file.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if ok && fn.Name.Name == "alpDecode"+name+"Generic" {
			body = src[fset.Position(fn.Body.Lbrace).Offset+1 : fset.Position(fn.Body.Rbrace).Offset]
			break
		}
	}
	if body == nil {
		return fmt.Errorf("missing kernel template %s", name)
	}
	var out bytes.Buffer
	out.WriteString("// Code generated by go generate ./tsdb/chunkenc. DO NOT EDIT.\n\n")
	header, _, found := bytes.Cut(src, []byte("//go:build"))
	if !found {
		return fmt.Errorf("missing build constraint in %s", arch)
	}
	out.Write(header)
	fmt.Fprintf(&out, "//go:build go1.27 && goexperiment.simd && %s\n\npackage chunkenc\n\nimport \"simd/archsimd\"\n\n", arch)
	fmt.Fprintf(&out, "func alpDecode%s(dst []float64, words []uint64, width int, base int64, factor, exponent uint8) { alp%sWidths[width](dst, words, width, base, factor, exponent) }\n\n", name, name)
	fmt.Fprintf(&out, "var alp%sWidths = [...]alpKernel{alpDecode%sGeneric,\n", name, name)
	for width := 1; width <= 64; width++ {
		fmt.Fprintf(&out, "alpDecode%sWidth%d,\n", name, width)
	}
	out.WriteString("}\n\n")
	for width := 1; width <= 64; width++ {
		fmt.Fprintf(&out, "func alpDecode%sWidth%d(dst []float64, words []uint64, _ int, base int64, factor, exponent uint8) {\nconst width = %d\n", name, width, width)
		out.Write(body)
		out.WriteString("}\n\n")
	}
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile("alp_decode_"+strings.ToLower(name)+"_generated.go", formatted, 0o644)
}
